services:
  db:
    image: mariadb:10.6
    env_file:
      - config/secrets.env
    environment:
      MARIADB_DATABASE: ${MW_DB_NAME:-labki}
      MARIADB_USER: ${MW_DB_USER:-labki}
      MARIADB_PASSWORD: ${MW_DB_PASSWORD:-labki_pass}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-root_pass}
    volumes:
      - db-data:/var/lib/mysql

  wiki:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MEDIAWIKI_VERSION: ${MEDIAWIKI_VERSION:-1.41}
    image: labki/labki-wiki:dev
    ports:
      - "8080:80"
    env_file:
      - config/secrets.env
    # All MW_* envs are provided via env_file; avoid compose-time interpolation
    volumes:
      - ./images:/var/www/html/images
      - ./config:/var/www/html/config
    depends_on:
      - db

volumes:
  db-data:


