name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare secrets
        run: |
          cp config/secrets.env.example config/secrets.env

      - name: Build and start containers (clean)
        id: composeUp
        continue-on-error: true
        run: |
          docker compose down -v || true
          docker compose up -d --build --wait
          docker compose ps

      - name: Show Failed Healthcheck
        if: steps.composeUp.outcome == 'failure'
        run: |
          docker inspect labki-framework-wiki-1
          docker compose logs wiki
          exit 1

      - name: Verify LabkiPackManager extension loaded
        run: |
          docker compose exec -T wiki php maintenance/eval.php --conf /var/www/html/config/LocalSettings.php \
            'echo (MediaWiki\Registration\ExtensionRegistry::getInstance()->isLoaded("LabkiPackManager") ? "OK\n" : "FAIL\n");'

      - name: Cleanup
        if: always()
        run: |
          docker compose down -v
